sudo: required

language: csharp
mono: none
dotnet: 3.1

services: 
  - docker
before-install:
  - docker build -t asalihov/travis-aws-test -f Dockerfile.dev .
  
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test tests