sudo: required

language: csharp
mono: none
dotnet: 3.1

services: 
  - docker
before-install:
  - docker build -t asalihov/travis-aws-test -f Dockerfile.dev .
  
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test tests
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerTravisAws"
  env: "DockerTravisAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-916335024047"
  bucket_path: "DockerTravisAws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY